alter table EMAILTEMPLATES_EMAIL_TEMPLATE add ( EMAIL_BODY_REPORT_ID varchar2(32) ) ^
alter table EMAILTEMPLATES_EMAIL_TEMPLATE add ( HTML clob ) ^
alter table EMAILTEMPLATES_EMAIL_TEMPLATE add ( REPORT_XML clob ) ^
