alter table EMAILTEMPLATES_EMLTPTE_FDLINK add constraint FK_EMATEMFI_EMAIL_TEMPLATE foreign key (EMAIL_TEMPLATE_ID) references EMAILTEMPLATES_EMAIL_TEMPLATE(ID)^
alter table EMAILTEMPLATES_EMLTPTE_FDLINK add constraint FK_EMATEMFI_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID)^
