alter table EMAILTEMPLATES_TEMPLATE_BLOCK add constraint FK_EMAILTEMPLATES_TEMBLO_CAT foreign key (CATEGORY_ID) references EMAILTEMPLATES_BLOCK_GROUP(ID)^
create unique index IDX_EMAILTEMPLATES_TEBL_UK_NA on EMAILTEMPLATES_BLOCK_GROUP (NAME, DELETE_TS) ^
create index IDX_EMAILTEMPLATES_TEMBLO_CAT on EMAILTEMPLATES_TEMPLATE_BLOCK (CATEGORY_ID)^
