-- begin YET_CONTENT_EMAIL_TEMPLATE
alter table YET_CONTENT_EMAIL_TEMPLATE add constraint FK_YET_CONTENT_EMAIL_TEMPLATE_ON_GROUP foreign key (GROUP_ID) references REPORT_GROUP(ID)^
alter table YET_CONTENT_EMAIL_TEMPLATE add constraint FK_YET_CONTENT_EMAIL_TEMPLATE_ON_REPORT foreign key (REPORT_ID) references REPORT_REPORT(ID)^
create index IDX_YET_CONTENT_EMAIL_TEMPLATE_ON_GROUP on YET_CONTENT_EMAIL_TEMPLATE (GROUP_ID)^
create index IDX_YET_CONTENT_EMAIL_TEMPLATE_ON_REPORT on YET_CONTENT_EMAIL_TEMPLATE (REPORT_ID)^
-- end YET_CONTENT_EMAIL_TEMPLATE
-- begin YET_LAYOUT_EMAIL_TEMPLATE
alter table YET_LAYOUT_EMAIL_TEMPLATE add constraint FK_YET_LAYOUT_EMAIL_TEMPLATE_ON_GROUP foreign key (GROUP_ID) references REPORT_GROUP(ID)^
alter table YET_LAYOUT_EMAIL_TEMPLATE add constraint FK_YET_LAYOUT_EMAIL_TEMPLATE_ON_REPORT foreign key (REPORT_ID) references REPORT_REPORT(ID)^
create index IDX_YET_LAYOUT_EMAIL_TEMPLATE_ON_GROUP on YET_LAYOUT_EMAIL_TEMPLATE (GROUP_ID)^
create index IDX_YET_LAYOUT_EMAIL_TEMPLATE_ON_REPORT on YET_LAYOUT_EMAIL_TEMPLATE (REPORT_ID)^
-- end YET_LAYOUT_EMAIL_TEMPLATE
-- begin YET_CONTENT_EMAIL_TEMPLATE_REPORT_LINK
alter table YET_CONTENT_EMAIL_TEMPLATE_REPORT_LINK add constraint FK_CONEMATEMREP_ON_CONTENT_EMAIL_TEMPLATE foreign key (CONTENT_EMAIL_TEMPLATE_ID) references YET_CONTENT_EMAIL_TEMPLATE(ID)^
alter table YET_CONTENT_EMAIL_TEMPLATE_REPORT_LINK add constraint FK_CONEMATEMREP_ON_REPORT foreign key (REPORT_ID) references REPORT_REPORT(ID)^
-- end YET_CONTENT_EMAIL_TEMPLATE_REPORT_LINK
